### ISSUE TITLE
Script errors out on missing Master File

### ISSUE THREAD

**Issue by whoismattclark** [jensb/iphoto2xmp#11]
```
EVENT: My Photo Stream (thumb: Iub64t+…): 2017-02-11 .. 2017-05-31
 129139(62385): IMG_4899.JPG	IMG_4899	0* 5%ksiQ…/0r8U7g…	taken:20170211-184045-0600 edit:20170212-004045-0600 import:20170212-194625-0600	
  Orig: 2448x3264 (1.0000/1.0000), Masters/Users/xxxxxxxxx/Library/Application Support/iLifeAssetManagement/assets/sub/01c1c230083779c93adb668e7d090ecb794393e223/IMG_4899.JPG (missing)
  Mod : 2448x3264, Previews/Users/xxxxxxxxx/Library/Application Support/iLifeAssetManagement/assets/sub/01c1c230083779c93adb668e7d090ecb794393e223/5%ksiQ89Tsy72VWle3%TjQ/IMG_4899.JPG (missing)
  Flip: EXIF °/°, photo 0°, face(s): 0°
  GPS : lat: lng:, 
iphoto2xmp.rb:606:in `block (2 levels) in <main>': undefined method `[]' for nil:NilClass (NoMethodError)
	from iphoto2xmp.rb:604:in `each'
	from iphoto2xmp.rb:604:in `inject'
	from iphoto2xmp.rb:604:in `block in <main>'
	from iphoto2xmp.rb:418:in `each'
	from iphoto2xmp.rb:418:in `<main>'
```

**Comment by whoismattclark** [comment]
Lovin' this script.  I'm very much looking forward to leaving the Apple media ecosystem.  Thanks for your help.

**Comment by whoismattclark** [comment]
I rebuilt my iPhoto library and reran the script.  Problem did not recur.
