### ISSUE TITLE
Compatibility with OSX 10.11.6?

### ISSUE THREAD

**Issue by IanGame** [jensb/iphoto2xmp#9]
Hi, thanks for putting this up. 

My objective is to simply read all the filenames from iPhotos to confirm the sync with a backup storage area and thought your Ruby app would at least start me in the right direction. However, the first problem I am finding is the some of the fields in the RKVersion db do not exist so the Ruby script fails at various points when attempting to run. An example: 'isOriginal' is not there. A similar situation with RKMaster: 'type' does not exist.

I would appreciate any pointers as to what the best approach would be please.

Thanks

ian

**Comment by jensb** [comment]
Hi,
I haven't tried Photos yet, the database format seems to be a little different. But I should be able to make it compatible. Can you create a small Photos database (suitable for sharing - no private photos ;) ) with comments, ratings, etc., zip it up, and share it with me?

**Comment by IanGame** [comment]
Hello, Thanks for your offer. I attach 5 photos with various edits and comments. I also attach the schema from my Library.apdb as a formatted file 'dump.txt'.

[Archive.zip](https://github.com/jensb/iphoto2xmp/files/706105/Archive.zip)
[dump.txt](https://github.com/jensb/iphoto2xmp/files/706106/dump.txt)

Thanks

Ian

**Comment by jensb** [comment]
The Archive.zip does contain some images, but I would need the actual "~/Pictures/Photos Library" folder (zipped) with all the .apdb and metadata files. If it's just about EXIF data you don't need a converter, most image software can read it directly ;)
I have now converted my test library to Photos now, I will see what I can do.

**Comment by IanGame** [comment]
OK thanks I didn't read your request closely, you need the whole library. I will respond later with that as it may help. I did read the file list using sqlite3 and could pursue that option but I would still be interested in using your project. 

Sent from my HTC

----- Reply message -----

**Comment by jensb** [comment]
Closing due to inactivity.
If this issue is still relevant, please reopen.

**Comment by mlevin77** [comment]
I am still extremely interested in getting this working on Apple OS. I've been going crazy with the various requirements issues (incompatible versions, path files, etc. etc.) and can't get it to run on any of my OS versions.

**Comment by jensb** [comment]
It is running fine on my Macbook Pro (MacOS 10.12.6)  using MacPorts & Ruby 2.5. And it was pretty straight foward, as documented. I just recently installed Ubuntu 18.04 (fresh, no upgrade) and there it also worked within 5 minutes.
My advice for MacOS would be to completely uninstall any Homebrew, RVM, whatever environments (unless you need them for anything else) that you installed just to get Ruby, completely ignore the Ruby that Apple shipped, and then get MacPorts and proceed as documented in the README. As far as I am concerned, there is no need to tweak library paths or anything, but it is very easy to mix up and confuse all the different Ruby variants (and installation methods) that exist.

**Comment by mlevin77** [comment]
1) I don't suppose there's a Ruby compiler, so that anyone who has it running on their Mac could send me an executable?

2) re. "completely uninstall any Homebrew, RVM" - how to do that? I'm pretty new to those and I have no idea how to make sure it's all gone. I'd love to clean it out and start fresh!

**Comment by mlevin77** [comment]
I think I removed everything and tried from scratch with Macports; I see:

$ sudo gem2.5 install exifr
Successfully installed exifr-1.3.4
Parsing documentation for exifr-1.3.4
Done installing documentation for exifr after 0 seconds
1 gem installed
bash-3.2$ sudo /usr/bin/ruby iphoto2xmp.rb~ "/Volumes/LaCie\ scratch\ disk/iPhoto\ library" "/Volumes/LaCie\ scratch\ disk/test/"
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- exifr/jpeg (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from iphoto2xmp.rb~:24:in `<main>'
bash-3.2$ sudo gem2.5 install exifr/jpeg
ERROR:  Could not find a valid gem 'exifr/jpeg' (>= 0) in any repository

**Comment by jensb** [comment]
you have to use ruby2.5, if you used gem2.5, and it is probably located in /opt/local/bin, try without a path (and without `sudo`).

And install the last missing gem, the README contained another error (sorry!):
It's `fileutils`, not `findutils`. Argh. :-(
But now I think we have everything set up. Does it work after installing the `fileutils` gem?

**Comment by mlevin77** [comment]
Do I need to use sudo?  I installed fileutils and am using ruby2.5:

$ /opt/local/bin/ruby2.5 iphoto2xmp.rb~ "/Volumes/LaCie\ scratch\ disk/iPhoto\ library" "/Volumes/LaCie\ scratch\ disk/test/"
Traceback (most recent call last):
	16: from iphoto2xmp.rb~:19:in `<main>'
	15: from /opt/local/lib/ruby2.5/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	14: from /opt/local/lib/ruby2.5/2.5.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	13: from /opt/local/lib/ruby2.5/2.5.0/rubygems.rb:213:in `try_activate'
	12: from /opt/local/lib/ruby2.5/2.5.0/rubygems/specification.rb:1063:in `find_by_path'
	11: from /opt/local/lib/ruby2.5/2.5.0/rubygems/specification.rb:850:in `stubs'
	10: from /opt/local/lib/ruby2.5/2.5.0/rubygems/specification.rb:782:in `installed_stubs'
	 9: from /opt/local/lib/ruby2.5/2.5.0/rubygems/specification.rb:790:in `map_stubs'
	 8: from /opt/local/lib/ruby2.5/2.5.0/rubygems/specification.rb:790:in `flat_map'
	 7: from /opt/local/lib/ruby2.5/2.5.0/rubygems/specification.rb:790:in `each'
	 6: from /opt/local/lib/ruby2.5/2.5.0/rubygems/specification.rb:793:in `block in map_stubs'
	 5: from /opt/local/lib/ruby2.5/2.5.0/rubygems/specification.rb:768:in `gemspec_stubs_in'
	 4: from /opt/local/lib/ruby2.5/2.5.0/rubygems/specification.rb:768:in `select'
	 3: from /opt/local/lib/ruby2.5/2.5.0/rubygems/stub_specification.rb:208:in `valid?'
	 2: from /opt/local/lib/ruby2.5/2.5.0/rubygems/stub_specification.rb:118:in `data'
	 1: from /opt/local/lib/ruby2.5/2.5.0/rubygems/stub_specification.rb:118:in `open'
/opt/local/lib/ruby2.5/2.5.0/rubygems/stub_specification.rb:118:in `initialize': Permission denied @ rb_sysopen - /opt/local/lib/ruby2.5/gems/2.5.0/specifications/CFPropertyList-3.0.0.gemspec (Errno::EACCES)

     what's this permission error?

**Comment by jensb** [comment]
These files should be readable by anybody, as in my install. 
What does `ls -l /opt/local/lib/ruby2.5/gems/2.5.0/specifications/` say? If you get permission denied, also try `sudo ls -l ...`.

**Comment by mlevin77** [comment]
$ ls -l /opt/local/lib/ruby2.5/gems/2.5.0/specifications/
total 112
-rw-------   1 root  admin  1284 Sep  2 14:24 CFPropertyList-3.0.0.gemspec
drwxr-xr-x  24 root  admin   816 Sep  1 16:43 default
-rw-r--r--   1 root  admin  1518 Jun 19 15:36 did_you_mean-1.2.0.gemspec
-rw-------   1 root  admin  1642 Sep  2 14:30 exifr-1.3.4.gemspec
-rw-------   1 root  admin  1279 Sep  2 15:32 fileutils-1.1.0.gemspec
-rw-r--r--   1 root  admin  4910 Jun 19 15:36 minitest-5.10.3.gemspec
-rw-r--r--   1 root  admin  1255 Jun 19 15:36 net-telnet-0.1.1.gemspec
-rw-r--r--   1 root  admin  2265 Jun 19 15:36 power_assert-1.1.1.gemspec
-rw-------   1 root  admin  4305 Sep  2 14:24 progressbar-1.10.0.gemspec
-rw-r--r--   1 root  admin  2611 Jun 19 15:36 rake-12.3.0.gemspec
-rw-------   1 root  admin  3427 Sep  2 14:24 sqlite3-1.3.13.gemspec
-rw-r--r--   1 root  admin  2368 Jun 19 15:36 test-unit-3.2.7.gemspec
-rw-r--r--   1 root  admin  1584 Jun 19 15:36 xmlrpc-0.3.0.gemspec

$ sudo ls -l /opt/local/lib/ruby2.5/gems/2.5.0/specifications/
Password:
total 112
-rw-------   1 root  admin  1284 Sep  2 14:24 CFPropertyList-3.0.0.gemspec
drwxr-xr-x  24 root  admin   816 Sep  1 16:43 default
-rw-r--r--   1 root  admin  1518 Jun 19 15:36 did_you_mean-1.2.0.gemspec
-rw-------   1 root  admin  1642 Sep  2 14:30 exifr-1.3.4.gemspec
-rw-------   1 root  admin  1279 Sep  2 15:32 fileutils-1.1.0.gemspec
-rw-r--r--   1 root  admin  4910 Jun 19 15:36 minitest-5.10.3.gemspec
-rw-r--r--   1 root  admin  1255 Jun 19 15:36 net-telnet-0.1.1.gemspec
-rw-r--r--   1 root  admin  2265 Jun 19 15:36 power_assert-1.1.1.gemspec
-rw-------   1 root  admin  4305 Sep  2 14:24 progressbar-1.10.0.gemspec
-rw-r--r--   1 root  admin  2611 Jun 19 15:36 rake-12.3.0.gemspec
-rw-------   1 root  admin  3427 Sep  2 14:24 sqlite3-1.3.13.gemspec
-rw-r--r--   1 root  admin  2368 Jun 19 15:36 test-unit-3.2.7.gemspec
-rw-r--r--   1 root  admin  1584 Jun 19 15:36 xmlrpc-0.3.0.gemspec

**Comment by jensb** [comment]
Do `sudo chmod a+r /opt/local/lib/ruby2.5/gems/2.5.0/specifications/*  /opt/local/lib/ruby2.5/gems/2.5.0/specifications/default/*`
I hope these permissions errors are all there are. I wonder why they are only readably by root, this should not be the case.

**Comment by mlevin77** [comment]
bash-3.2$ sudo chmod a+r /opt/local/lib/ruby2.5/gems/2.5.0/specifications/*
Password:
bash-3.2$ /opt/local/bin/ruby2.5 iphoto2xmp.rb "/Volumes/LaCie\ scratch\ disk/iPhoto\ library" "/Volumes/LaCie\ scratch\ disk/test/"
Ignoring sqlite3-1.3.13 because its extensions are not built. Try: gem pristine sqlite3 --version 1.3.13
Traceback (most recent call last):
2: from iphoto2xmp.rb~:19:in `<main>'
1: from /opt/local/lib/ruby2.5/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/opt/local/lib/ruby2.5/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- progressbar (LoadError)

   even though I installed progressbar:

bash-3.2$ sudo gem2.5 install progressbar
Successfully installed progressbar-1.10.0
Parsing documentation for progressbar-1.10.0
Done installing documentation for progressbar after 0 seconds
1 gem installed

**Comment by mlevin77** [comment]
ok so I went and found progressbar manually, and added this to the .rb file:

$LOAD_PATH.unshift('/opt/local/lib/ruby2.5/gems/2.5.0/gems/progressbar-1.10.0/lib/ruby-progressbar/')
$LOAD_PATH.unshift('/opt/local/lib/ruby2.5/gems/2.5.0/gems/progressbar-1.10.0/lib/')

    now it seems to run, but it gives an error:

bash-3.2$ ls -ld /Volumes/LaCie\ scratch\ disk/test/
drwxr-xr-x  2 mlevin  rvm  68 Jul  7 06:25 /Volumes/LaCie scratch disk/test/

  so my destination folder exists, but:

bash-3.2$ sudo /opt/local/bin/ruby2.5 iphoto2xmp.rb "/Volumes/LaCie\ scratch\ disk/iPhoto\ library" "/Volumes/LaCie\ scratch\ disk/test"
Traceback (most recent call last):
	1: from iphoto2xmp.rb:40:in `<main>'
iphoto2xmp.rb:40:in `mkdir': No such file or directory @ dir_s_mkdir - /Volumes/LaCie\ scratch\ disk/test (Errno::ENOENT)

**Comment by mlevin77** [comment]
Even though my output directory existed, I tried a simpler output directory, in /tmp/ and now I see this:

bash-3.2$ sudo /opt/local/bin/ruby2.5 iphoto2xmp.rb "/Volumes/LaCie\ scratch\ disk/iPhoto\ library" "/tmp/test"
Reading iPhoto database ...
Traceback (most recent call last):
	2: from iphoto2xmp.rb:246:in `<main>'
	1: from iphoto2xmp.rb:246:in `new'
iphoto2xmp.rb:246:in `initialize': unable to open database file (SQLite3::CantOpenException)

but the input data exist too:

bash-3.2$ ls -al /Volumes/LaCie\ scratch\ disk/iPhoto\ library
total 115896
drwxr-x--x@ 32 mlevin   rvm      1088 Aug  4 05:05 .
drwxrwxr-x  17 initial  rvm       646 Aug  5 07:12 ..
-rw-r--r--@  1 mlevin   rvm     12292 Mar 16 01:58 .DS_Store
-rw-r--r--@  1 mlevin   rvm        16 Mar 15 23:03 .ipspot_update
-rw-r--r--@  1 mlevin   rvm  42316730 Aug  4 05:03 AlbumData.xml
drwxr-xr-x   2 mlevin   rvm        68 Mar 16 05:37 Attachments
drwxrwxrwx   2 mlevin   rvm        68 Sep 19  2012 Auto Import
drwxr-x--x   6 mlevin   rvm       204 Mar 16 06:05 Backup
drwxrwxrwx   3 mlevin   rvm       102 Jul  2  2016 Contents
lrw-rw-rw-   1 mlevin   rvm        14 Jul  2  2016 Data -> ./Data.noindex
lrwxr-xr-x   1 mlevin   rvm        12 Mar 16 05:37 Data.noindex -> ./Thumbnails
drwxr-xr-x  21 mlevin   rvm       714 Aug  4 05:05 Database
-rw-r--r--@  1 mlevin   rvm       324 Mar 17 06:01 Info.plist
-rw-r-----@  1 mlevin   rvm        22 Mar 16 06:05 Library.data
-rw-r-----@  1 mlevin   rvm        22 Mar 16 06:05 Library.iPhoto
-rw-r-----@  1 mlevin   rvm        12 Mar 16 06:05 Library6.iPhoto
drwxr-xr-x  24 mlevin   rvm       816 Jan 23  2018 Masters
drwxr-xr-x  13 mlevin   rvm       442 Mar 14 22:01 Metadata Backup
lrwxr-xr-x   1 mlevin   rvm        10 Mar 16 05:37 Modified -> ./Previews
lrwxr-xr-x   1 mlevin   rvm         9 Mar 16 05:37 Originals -> ./Masters
drwxr-xr-x  24 mlevin   rvm       816 Jan 23  2018 Previews
drwxr-xr-x@  3 mlevin   rvm       102 Jul 24 06:30 ProjectCache
-rw-r--r--@  1 mlevin   rvm       341 Mar 16 06:03 ProjectDBVersion.plist
-rw-r--r--@  1 mlevin   rvm    802816 Aug  4 05:05 Projects.db
-rw-r--r--@  1 mlevin   rvm  16066091 Jul  2  2016 ThemeCache
drwxr-xr-x  25 mlevin   rvm       850 Mar 16 06:03 Thumbnails
-rw-r--r--   1 mlevin   rvm       552 Jul  2  2016 com.apple.iPhoto.plist
drwxr-xr-x   4 mlevin   rvm       136 Aug  4 05:03 iLifeShared
-rw-r--r--@  1 mlevin   rvm     16384 Mar 16 06:05 iPhotoAux.db
-rw-r--r--@  1 mlevin   rvm         1 Aug  4 05:05 iPhotoLock.data
-rw-r-----@  1 mlevin   rvm     65536 Mar 16 06:05 iPhotoMain.db
drwxr-xr-x@ 56 mlevin   rvm      1904 Jul 27 14:49 iPod Photo Cache

**Comment by jensb** [comment]
It is possible that the script doesn't like space characters (or any other non-alphanumeric) in the directory names. I didn't check yet, these would need special treatment. But you can do `cd /Volumes/LaCie\ scratch\ disk` and then execute my script from there, just using relative path names ("iPhoto Library", "test") as parameters.

Also, your sqlite3 library seems broken (why?). The error message contains a suggestion:
"Ignoring sqlite3-1.3.13 because its extensions are not built. Try: gem pristine sqlite3 --version 1.3.13"

Try this maybe?

**Comment by mlevin77** [comment]
bash-3.2$ sudo gem2.5 pristine sqlite3 --version 1.3.13
Restoring gems to pristine condition...
Building native extensions. This could take a while...
Restored sqlite3-1.3.13

What do I do with the spaces in the names - do I need to try moving the huge library to a directory/disk with no spaces or is there an escape character or something I can use? Actually, doesn't the default example "iPhoto ilbrary" have a space?

**Comment by mlevin77** [comment]
Ok so I removed spaces from the destination and source directories, and it started working! Definite progress. After a while though, it stopped with an error:

Reading iPhoto database ...
Traceback (most recent call last):
	2: from iphoto2xmp.rb:246:in `<main>'
	1: from iphoto2xmp.rb:246:in `new'
iphoto2xmp.rb:246:in `initialize': unable to open database file (SQLite3::CantOpenException)
bash-3.2$ DEBUG=1 sudo /opt/local/bin/ruby2.5 iphoto2xmp.rb "/Volumes/LaCieScratchDisk/iPhotoLibrary" "/tmp/test"
Reading iPhoto database ...
Traceback (most recent call last):                                                                                                                               |
	4: from iphoto2xmp.rb:412:in `<main>'
	3: from iphoto2xmp.rb:412:in `each'
	2: from iphoto2xmp.rb:445:in `block in <main>'
	1: from iphoto2xmp.rb:75:in `link_photo'
iphoto2xmp.rb:128:in `parse_date': undefined method `parse' for Time:Class (NoMethodError)

any ideas?

**Comment by mlevin77** [comment]
I tried it again with DEBUG=3 hoping for more info, and saw this:

bash-3.2$ DEBUG=3 sudo /opt/local/bin/ruby2.5 iphoto2xmp.rb "/Volumes/LaCieScratchDisk/iPhotoLibrary" "/tmp/test2"
Password:
Reading iPhoto database ...
Traceback (most recent call last):                                                                                                                               |
	4: from iphoto2xmp.rb:412:in `<main>'
	3: from iphoto2xmp.rb:412:in `each'
	2: from iphoto2xmp.rb:445:in `block in <main>'
	1: from iphoto2xmp.rb:75:in `link_photo'
iphoto2xmp.rb:128:in `parse_date': undefined method `parse' for Time:Class (NoMethodError)

**Comment by jensb** [comment]
Did you modify iphoto2xmp.rb? Please download the most recent version from the 'Code' tab.
`require 'time'` should take care of this methd, and the `Time` class is installed by default. It works fine on my Macbook Pro ...

**Comment by mlevin77** [comment]
Got it! It's doing better this time:
$ ls
LICENSE				README.md			decode_plist_hash.rb		iphoto2xmp.rb			iphoto2xmp_template.xmp.erb
bash-3.2$ DEBUG=3 sudo /opt/local/bin/ruby2.5 iphoto2xmp.rb "/Volumes/LaCieScratchDisk/iPhotoLibrary" "/Volumes/LaCieScratchDisk/test5"
Password:
Reading iPhoto database ...
Exporting: |                                                                                                                                                     |

   so more is happening than before!  But, I thought the DEBUG would let it print progress info as it works - I'm seeing no output at all; is there some way of knowing what it's doing and seeing that it's making progress?

**Comment by jensb** [comment]
I'll take a wild guess and say the DEBUG variable isn't taken over by `sudo`.
Do you *have* to use `sudo` or can you just adjust the file permissions?
If you have to use `sudo` , try `sudo bash` and then type `DEBUG=3 /opt/local/bin/ruby2.5 ...` from within the admin shell. 
or `export DEBUG=3 ; /opt/local/bin/ruby2.5 iphoto2xmp.rb ...` to make DEBUG persistent within the shell session.
PS: the "DEBUG" variable isn't some magical Ruby thing, it's just a variable I query in my script to decide how much screen output to generate.

**Comment by mlevin77** [comment]
great! This worked. But it gets stuck:

 121(1987): Young Leah	Young Leah	3* 754B0C…/7dyUkM…	taken:20060604-072815-0400 edit:20060616-151358-0400 import:20160702-190902-0400	
  Orig: 1539x922 (1.0000/1.0000), Masters/2006/Some historical family stuff/Young Leah (found)
     => 1978/Some historical family stuff/Young Leah
  Mod : 1539x922, Previews/2006/Some historical family stuff/754B0C2D-EAC4-4C61-A01C-48F4BC86C863/Young Leah (missing)
  Flip: EXIF °/°, photo 0°, face(s): 0°
  GPS : lat: lng:, 
  Tags: Historical Family(18)
  Edit:  
  ... Original Face DB data:
  ...     face: tl: 0.362256 0.619233, wh: 0.045553 0.027290,    (11775)
  ...     face: tl: 0.267896 0.627680, wh: 0.043384 0.025991,    (11776)
  ...  modface: tl: 0.361171 0.619233, wh: 0.045553 0.027290,    (11775)
  ...  modface: tl: 0.266811 0.627680, wh: 0.043384 0.025991,    (11776)
  ... After processing:
  ... Face0°: tl: 0.362256 0.619233, wh: 0.045553 0.027290;	 [0]
  ... Face0°: tl: 0.267896 0.627680, wh: 0.043384 0.025991;	 [0]
  ... FaceEdit : tl: 0.361171 0.619233, wh: 0.045553 0.027290;	 [mod]
  ... FaceEdit : tl: 0.266811 0.627680, wh: 0.043384 0.025991;	 [mod]

It creates a few files/folders, but then just sits there after this one - no more output, nothing seems to be happening. How to know what is going on?

**Comment by jensb** [comment]
I wouldn't dare to guess .. :) there might be an extremely large image, or a read error, or a bug in the app causing it to run away in an endless loop, ... how long did you wait? Wait for at least one minute and watch your CPU load, and tell me what happened and how busy your computer was during that time.
Also, try running it without "DEBUG=...".

**Comment by mlevin77** [comment]
Well, I left it overnight and still nothing has happened, so I don't think it's a matter of waiting longer. The computer wasn't doing much of anything else during this time.  I tried it without DEBUG and the CPU load went from 3% to about 6%, but it appears to be stuck in the same place. Any way to have it print more debugging info so we can see where it sticks?  Or, to give it a restriction parameter (for example, export only photos from a certain year) to see if it's a particular photo that it hanging it?

**Comment by jensb** [comment]
If I had access to the database I'd just insert more debugging output. It might be the write process of the XMP sidecar files, is your disk full or almost full? It might be accessing more of the iPhoto SQLite databases is causing problems.
Can you make your iPhoto database available (to me, privately, of course) as an archive (.7z or tar.bz2 is probably best) **without** the actual photos (folders "Originals", "Masters", "Modified" etc)? I'll try to find the problem then.

**Comment by mlevin77** [comment]
Thanks! My disk is not full.  Sure, I can send you the database without the images (the actual thing is huge).  Which actual files/folders should I zip for you?

**Comment by jensb** [comment]
I don't need Masters, Originals, Previews, Thumbnails, "IPod Photo Cache" and Modified folders (those should be the largest size). I need the "Database" contents (especially "Database/apdb") and "Albumdata.xml". Possibly "ILifeShared" for debugging since it contains a reduced Albumdata.xml file.
Thanks!

Upload your archive here: https://root.rb-hosting.de/nextcloud/index.php/s/Cr8munQvFNYSEuc
(It's upload only so you will not see the results)

**Comment by mlevin77** [comment]
Ok I've selected the ZIP file, but I can't tell if it's doing anything - it's a big file and I see no evidence of it uploading anything. Can you shoot me an email and I'll send you a Dropbox download link?

**Comment by jensb** [comment]
There should be a small animated progress spinner below the link if it's uploading. Anyway, jens-github AT spamfreemail DOT de also works.

**Comment by jensb** [comment]
I got your archive and iphoto2xmp went through it without a fuss.
I requested some additional library data via private email, I'll update this when we can close the bug.

**Comment by alexantao** [comment]
Hi ! 
I’m interested in migrating my Photos (not iPhoto) Library to digiKam. Does this script work with Photos for Mac ? I’m running High Sierra and my Library e very huge, more than 100.000 photos and lot of álbuns.
Thanks
